name: aqi
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - autocommand=2.2.2
  - backports=1.0
  - backports.tarfile=1.2.0
  - backports.zstd=1.5.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.5.20
  - cairo=1.18.4
  - certifi=2026.5.20
  - cffi=2.0.0
  - charset-normalizer=3.4.7
  - cheroot=11.1.2
  - cherrypy=18.10.0
  - colorama=0.4.6
  - cryptography=48.0.0
  - cyrus-sasl=2.1.28
  - dbus=1.16.2
  - dbus-python=1.3.2
  - exceptiongroup=1.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.3
  - idna=3.15
  - iniconfig=2.3.0
  - jaraco.classes=3.4.0
  - jaraco.collections=5.2.1
  - jaraco.context=6.1.2
  - jaraco.functools=4.5.0
  - jaraco.text=4.0.0
  - keyutils=1.6.3
  - krb5=1.22.2
  - ld_impl_linux-64=2.45.1
  - libblas=3.11.0
  - libcblas=3.11.0
  - libedit=3.1.20250104
  - libexpat=2.8.1
  - libffi=3.5.2
  - libfreetype=2.14.3
  - libfreetype6=2.14.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgirepository=1.86.0
  - libglib=2.88.1
  - libgomp=15.2.0
  - libiconv=1.18
  - liblapack=3.11.0
  - liblzma=5.8.3
  - libmpdec=4.0.0
  - libntlm=1.8
  - libopenblas=0.3.33
  - libpng=1.6.58
  - libpq=18.4
  - libsqlite=3.53.1
  - libstdcxx=15.2.0
  - libuuid=2.42.1
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.2
  - more-itertools=11.0.2
  - ncurses=6.6
  - numpy=2.4.6
  - openldap=2.6.13
  - openssl=3.6.2
  - packaging=26.2
  - pandas=3.0.3
  - pcre2=10.47
  - pip=26.1.1
  - pixman=0.46.4
  - pluggy=1.6.0
  - portend=3.2.1
  - psycopg2=2.9.11
  - pthread-stubs=0.4
  - pycairo=1.29.0
  - pycparser=3.0
  - pygments=2.20.0
  - pygobject=3.56.3
  - pyopenssl=26.2.0
  - pyserial=3.5
  - pysocks=1.7.1
  - pytest=9.0.3
  - python=3.14.5
  - python-dateutil=2.9.0.post0
  - python_abi=3.14
  - pyyaml=6.0.3
  - readline=8.3
  - repoze.lru=0.8
  - requests=2.34.2
  - routes=2.5.1
  - setuptools=82.0.1
  - simplejson=4.1.1
  - six=1.17.0
  - tempora=5.9.0
  - tk=8.6.13
  - tomli=2.4.1
  - typing_extensions=4.15.0
  - tzdata=2025c
  - urllib3=2.7.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.13
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxrender=0.9.12
  - yaml=0.2.5
  - zc.lockfile=4.0
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.2
      - aiohttp==3.13.5
      - aiosignal==1.4.0
      - attrs==26.1.0
      - frozenlist==1.8.0
      - multidict==6.7.1
      - propcache==0.5.2
      - python-aqi==0.6.1
      - tplink-cloud-api==5.2.0
      - yarl==1.24.2
